DEBUG 2017-04-11 04:17:26,190: 	 Executing command: 'submit'
DEBUG 2017-04-11 04:17:26,190: 	 Found CRAB cache file /afs/cern.ch/user/b/btran/.crab3
DEBUG 2017-04-11 04:17:26,198: 	 Checking credentials
DEBUG 2017-04-11 04:17:26,199: 	 Found proxy file /tmp/x509up_u80051
DEBUG 2017-04-11 04:17:26,199: 	 Getting proxy life time left
DEBUG 2017-04-11 04:17:26,702: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -timeleft
 output : 604651

 error: 
 retcode : 0
DEBUG 2017-04-11 04:17:27,206: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -actimeleft
 output : 604649

 error: 
 retcode : 0
DEBUG 2017-04-11 04:17:27,207: 	 Proxy valid for 167:57:31 hours
INFO 2017-04-11 04:17:27,207: 	 Will use CRAB configuration file crab3_xi_analyzer.py
DEBUG 2017-04-11 04:17:27,207: 	 Loading CRAB configuration file.
DEBUG 2017-04-11 04:17:27,212: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-04-11 04:17:27,212: 	 Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST/crab_HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST' already exists 
Please change the requestName in the config file
ERROR 2017-04-11 04:17:27,212: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST/crab_HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST' already exists 
Please change the requestName in the config file
DEBUG 2017-04-11 05:50:08,675: 	 Executing command: 'submit'
DEBUG 2017-04-11 05:50:08,676: 	 Found CRAB cache file /afs/cern.ch/user/b/btran/.crab3
DEBUG 2017-04-11 05:50:08,706: 	 Checking credentials
DEBUG 2017-04-11 05:50:08,706: 	 Found proxy file /tmp/x509up_u80051
DEBUG 2017-04-11 05:50:08,706: 	 Getting proxy life time left
DEBUG 2017-04-11 05:50:09,416: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -timeleft
 output : 599088

 error: 
 retcode : 0
DEBUG 2017-04-11 05:50:09,922: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -actimeleft
 output : 599087

 error: 
 retcode : 0
DEBUG 2017-04-11 05:50:09,923: 	 Proxy valid for 166:24:48 hours
INFO 2017-04-11 05:50:09,923: 	 Will use CRAB configuration file crab3_xi_analyzer.py
DEBUG 2017-04-11 05:50:09,923: 	 Loading CRAB configuration file.
DEBUG 2017-04-11 05:50:09,926: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-04-11 05:50:09,927: 	 Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST/crab_HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST' already exists 
Please change the requestName in the config file
ERROR 2017-04-11 05:50:09,927: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST/crab_HLT185_220Correlationcascadev2ppb2016NopTcutPeakAndSidebandTESTTEST' already exists 
Please change the requestName in the config file
DEBUG 2017-04-12 02:42:09,901: 	 Executing command: 'submit'
DEBUG 2017-04-12 02:42:09,901: 	 Found CRAB cache file /afs/cern.ch/user/b/btran/.crab3
DEBUG 2017-04-12 02:42:09,910: 	 Checking credentials
DEBUG 2017-04-12 02:42:09,911: 	 Found proxy file /tmp/x509up_u80051
DEBUG 2017-04-12 02:42:09,911: 	 Getting proxy life time left
DEBUG 2017-04-12 02:42:10,627: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -timeleft
 output : 604771

 error: 
 retcode : 0
DEBUG 2017-04-12 02:42:11,338: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -actimeleft
 output : 604770

 error: 
 retcode : 0
DEBUG 2017-04-12 02:42:11,339: 	 Proxy valid for 167:59:31 hours
INFO 2017-04-12 02:42:11,339: 	 Will use CRAB configuration file crab3_xi_analyzer.py
DEBUG 2017-04-12 02:42:11,339: 	 Loading CRAB configuration file.
DEBUG 2017-04-12 02:42:11,341: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-04-12 02:42:11,341: 	 Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcutTest_scale/crab_HLT185_220Correlationcascadev2ppb2016NoXipTcutTest_scale' already exists 
Please change the requestName in the config file
ERROR 2017-04-12 02:42:11,341: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcutTest_scale/crab_HLT185_220Correlationcascadev2ppb2016NoXipTcutTest_scale' already exists 
Please change the requestName in the config file
DEBUG 2017-04-12 16:59:09,982: 	 Executing command: 'kill'
DEBUG 2017-04-12 16:59:09,984: 	 Found CRAB cache file /afs/cern.ch/user/b/btran/.crab3
DEBUG 2017-04-12 16:59:09,998: 	 Checking credentials
DEBUG 2017-04-12 16:59:10,001: 	 Found proxy file /tmp/x509up_u80051
DEBUG 2017-04-12 16:59:10,001: 	 Getting proxy life time left
DEBUG 2017-04-12 16:59:11,727: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -timeleft
 output : 603996

 error: 
 retcode : 0
DEBUG 2017-04-12 16:59:13,617: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -actimeleft
 output : 603994

 error: 
 retcode : 0
DEBUG 2017-04-12 16:59:13,617: 	 Proxy valid for 167:46:36 hours
ERROR 2017-04-12 16:59:13,623: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcut
ERROR 2017-04-12 16:59:13,623: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcut
DEBUG 2017-04-12 18:11:49,982: 	 Executing command: 'kill'
DEBUG 2017-04-12 18:11:49,983: 	 Found CRAB cache file /afs/cern.ch/user/b/btran/.crab3
DEBUG 2017-04-12 18:11:49,993: 	 Checking credentials
DEBUG 2017-04-12 18:11:49,993: 	 Found proxy file /tmp/x509up_u80051
DEBUG 2017-04-12 18:11:49,993: 	 Getting proxy life time left
DEBUG 2017-04-12 18:11:51,556: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -timeleft
 output : 599636

 error: 
 retcode : 0
DEBUG 2017-04-12 18:11:52,805: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -actimeleft
 output : 599635

 error: 
 retcode : 0
DEBUG 2017-04-12 18:11:52,806: 	 Proxy valid for 166:33:56 hours
ERROR 2017-04-12 18:11:52,810: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcut
ERROR 2017-04-12 18:11:52,810: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcut
DEBUG 2017-04-14 08:59:37,778: 	 Executing command: 'submit'
DEBUG 2017-04-14 08:59:37,779: 	 Found CRAB cache file /afs/cern.ch/user/b/btran/.crab3
DEBUG 2017-04-14 08:59:37,791: 	 Checking credentials
DEBUG 2017-04-14 08:59:37,792: 	 Found proxy file /tmp/x509up_u80051
DEBUG 2017-04-14 08:59:37,793: 	 Getting proxy life time left
DEBUG 2017-04-14 08:59:38,497: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -timeleft
 output : 595697

 error: 
 retcode : 0
DEBUG 2017-04-14 08:59:39,002: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -actimeleft
 output : 595696

 error: 
 retcode : 0
DEBUG 2017-04-14 08:59:39,003: 	 Proxy valid for 165:28:17 hours
INFO 2017-04-14 08:59:39,022: 	 Will use CRAB configuration file crab3_xi_analyzer.py
DEBUG 2017-04-14 08:59:39,022: 	 Loading CRAB configuration file.
DEBUG 2017-04-14 08:59:39,027: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-04-14 08:59:39,027: 	 Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcut/crab_HLT185_220Correlationcascadev2ppb2016NoXipTcut' already exists 
Please change the requestName in the config file
ERROR 2017-04-14 08:59:39,027: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016NoXipTcut/crab_HLT185_220Correlationcascadev2ppb2016NoXipTcut' already exists 
Please change the requestName in the config file
DEBUG 2017-04-18 09:18:37,763: 	 Executing command: 'submit'
DEBUG 2017-04-18 09:18:37,765: 	 Found CRAB cache file /afs/cern.ch/user/b/btran/.crab3
DEBUG 2017-04-18 09:18:37,776: 	 Checking credentials
DEBUG 2017-04-18 09:18:37,777: 	 Found proxy file /tmp/x509up_u80051
DEBUG 2017-04-18 09:18:37,777: 	 Getting proxy life time left
DEBUG 2017-04-18 09:18:38,381: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -timeleft
 output : 604743

 error: 
 retcode : 0
DEBUG 2017-04-18 09:18:38,985: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u80051 -actimeleft
 output : 604743

 error: 
 retcode : 0
DEBUG 2017-04-18 09:18:38,986: 	 Proxy valid for 167:59:03 hours
INFO 2017-04-18 09:18:38,986: 	 Will use CRAB configuration file crab3_xi_analyzer.py
DEBUG 2017-04-18 09:18:38,986: 	 Loading CRAB configuration file.
DEBUG 2017-04-18 09:18:39,015: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-04-18 09:18:39,017: 	 Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016Dataset6NoXipTcutRAMfix1NewModules/crab_HLT185_220Correlationcascadev2ppb2016Dataset6NoXipTcutRAMfix1NewModules' already exists 
Please change the requestName in the config file
ERROR 2017-04-18 09:18:39,017: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1704-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/btran/work/CMSSW_8_0_24/src/XiAnalyzer/XiAnalyzer/crab/HLT185_220Correlationcascadev2ppb2016Dataset6NoXipTcutRAMfix1NewModules/crab_HLT185_220Correlationcascadev2ppb2016Dataset6NoXipTcutRAMfix1NewModules' already exists 
Please change the requestName in the config file
